In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import re
from string import punctuation

In [38]:
df = pd.read_excel('dataset/dataspam.xlsx')[['pesan','label']]
df

                                                 pesan  label
0    Ayo klaim voucher diskon 50 ribunya sekarang, ...      1
1    Hari gini masih minta jajan sama ortu, Gak deh...      1
2    Instal snack Video diPlayStore atau dengan Ket...      1
3    Buka aplikasi SnackVideo, lalu log in dengan F...      1
4    Untuk Tips and Trik Join Grupnya sebelum posti...      1
..                                                 ...    ...
995  Selamat siang&#10;Izin gabung dan izin share&#...      1
996  Dijual Tanah Sawah Pinggir Jalan Raya&#10;Bisa...      1
997  Rumah dijual Bogor kota. Spesifikasi pada gamb...      1
998  jual tanah luas 25 hektar&#10;surat girik&#10;...      1
999  Assalamu'alaikum Warahmatullahi Wabarakatuh &#...      1

[1000 rows x 2 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   pesan   999 non-null    object
 1   label   1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [40]:
df.isna().sum()

pesan    1
label    0
dtype: int64

In [41]:
df.dropna(inplace=True)
df

                                                 pesan  label
0    Ayo klaim voucher diskon 50 ribunya sekarang, ...      1
1    Hari gini masih minta jajan sama ortu, Gak deh...      1
2    Instal snack Video diPlayStore atau dengan Ket...      1
3    Buka aplikasi SnackVideo, lalu log in dengan F...      1
4    Untuk Tips and Trik Join Grupnya sebelum posti...      1
..                                                 ...    ...
995  Selamat siang&#10;Izin gabung dan izin share&#...      1
996  Dijual Tanah Sawah Pinggir Jalan Raya&#10;Bisa...      1
997  Rumah dijual Bogor kota. Spesifikasi pada gamb...      1
998  jual tanah luas 25 hektar&#10;surat girik&#10;...      1
999  Assalamu'alaikum Warahmatullahi Wabarakatuh &#...      1

[999 rows x 2 columns]

In [42]:
X = df[['pesan']]
y = df.label

In [43]:
# def case_folding(text):
#     text = re.sub(r"http\S+","",text)
#     text = text.lower() # merubah bentuk menjadi lower case
#     text = re.sub(r'\d+', '', text) # menghapus angka
#     text = re.sub(r'[^\w\s]','',text) # menghapus karakter tanda baca
#     text = text.strip()
#     return text
# df['clean_text'] = list(map(case_folding,df['pesan']))
X

                                                 pesan
0    Ayo klaim voucher diskon 50 ribunya sekarang, ...
1    Hari gini masih minta jajan sama ortu, Gak deh...
2    Instal snack Video diPlayStore atau dengan Ket...
3    Buka aplikasi SnackVideo, lalu log in dengan F...
4    Untuk Tips and Trik Join Grupnya sebelum posti...
..                                                 ...
995  Selamat siang&#10;Izin gabung dan izin share&#...
996  Dijual Tanah Sawah Pinggir Jalan Raya&#10;Bisa...
997  Rumah dijual Bogor kota. Spesifikasi pada gamb...
998  jual tanah luas 25 hektar&#10;surat girik&#10;...
999  Assalamu'alaikum Warahmatullahi Wabarakatuh &#...

[999 rows x 1 columns]

In [44]:
X['text_lower'] =  X['pesan'].str.lower()

In [45]:
X

,pesan,text_lower
0,"Ayo klaim voucher diskon 50 ribunya sekarang, ...","ayo klaim voucher diskon 50 ribunya sekarang, ..."
1,"Hari gini masih minta jajan sama ortu, Gak deh...","hari gini masih minta jajan sama ortu, gak deh..."
2,Instal snack Video diPlayStore atau dengan Ket...,instal snack video diplaystore atau dengan ket...
3,"Buka aplikasi SnackVideo, lalu log in dengan F...","buka aplikasi snackvideo, lalu log in dengan f..."
4,Untuk Tips and Trik Join Grupnya sebelum posti...,untuk tips and trik join grupnya sebelum posti...
...,...,...
995,Selamat siang&#10;Izin gabung dan izin share&#...,selamat siang&#10;izin gabung dan izin share&#...
996,Dijual Tanah Sawah Pinggir Jalan Raya&#10;Bisa...,dijual tanah sawah pinggir jalan raya&#10;bisa...
997,Rumah dijual Bogor kota. Spesifikasi pada gamb...,rumah dijual bogor kota. spesifikasi pada gamb...
998,jual tanah luas 25 hektar&#10;surat girik&#10;...,jual tanah luas 25 hektar&#10;surat girik&#10;...
999,Assalamu'alaikum Warahmatullahi Wabarakatuh &#...,assalamu'alaikum warahmatullahi wabarakatuh &#...

In [46]:

# def remove_punctuation(text):
#     """custom function to remove the punctuation"""
#     text = str(text)
#     return text.translate(str.maketrans('', '', punctuation))

# df["punc"] = df["text_lower"].apply(lambda text: remove_punctuation(text))
# df.head()
def case_folding(text):
    text = re.sub(r"http\S+","",text)
    # text = text.lower() # merubah bentuk menjadi lower case
    text = re.sub(r'\d+', '', text) # menghapus angka
    text = re.sub(r'[^\w\s]','',text) # menghapus karakter tanda baca
    text = text.strip()
    return text
X['clean_text'] = list(map(case_folding,X['text_lower']))

In [47]:
X

,pesan,text_lower,clean_text
0,"Ayo klaim voucher diskon 50 ribunya sekarang, ...","ayo klaim voucher diskon 50 ribunya sekarang, ...",ayo klaim voucher diskon ribunya sekarang bia...
1,"Hari gini masih minta jajan sama ortu, Gak deh...","hari gini masih minta jajan sama ortu, gak deh...",hari gini masih minta jajan sama ortu gak dehh...
2,Instal snack Video diPlayStore atau dengan Ket...,instal snack video diplaystore atau dengan ket...,instal snack video diplaystore atau dengan ket...
3,"Buka aplikasi SnackVideo, lalu log in dengan F...","buka aplikasi snackvideo, lalu log in dengan f...",buka aplikasi snackvideo lalu log in dengan fb...
4,Untuk Tips and Trik Join Grupnya sebelum posti...,untuk tips and trik join grupnya sebelum posti...,untuk tips and trik join grupnya sebelum posti...
...,...,...,...
995,Selamat siang&#10;Izin gabung dan izin share&#...,selamat siang&#10;izin gabung dan izin share&#...,selamat siangizin gabung dan izin sharedijual ...
996,Dijual Tanah Sawah Pinggir Jalan Raya&#10;Bisa...,dijual tanah sawah pinggir jalan raya&#10;bisa...,dijual tanah sawah pinggir jalan rayabisa untu...
997,Rumah dijual Bogor kota. Spesifikasi pada gamb...,rumah dijual bogor kota. spesifikasi pada gamb...,rumah dijual bogor kota spesifikasi pada gamba...
998,jual tanah luas 25 hektar&#10;surat girik&#10;...,jual tanah luas 25 hektar&#10;surat girik&#10;...,jual tanah luas hektarsurat girikjual harga d...
999,Assalamu'alaikum Warahmatullahi Wabarakatuh &#...,assalamu'alaikum warahmatullahi wabarakatuh &#...,assalamualaikum warahmatullahi wabarakatuh dij...

fish: Command substitutions not allowed
nltk.download('indonesian')
             ^

In [49]:
data = pd.DataFrame({'Data':X.clean_text,'label':y}

In [51]:
data.to_csv('data_clean.csv',index=False)

In [22]:
def remove_number(text):
    a = ''.join(i for i in text if not i.isdigit())
    return a.strip()

df['remove_number'] =  df.punc.apply(remove_number)

In [23]:
df

,pesan,label,text_lower,punc,remove_number
0,"Ayo klaim voucher diskon 50 ribunya sekarang, ...",1,"ayo klaim voucher diskon 50 ribunya sekarang, ...",ayo klaim voucher diskon 50 ribunya sekarang b...,ayo klaim voucher diskon ribunya sekarang bia...
1,"Hari gini masih minta jajan sama ortu, Gak deh...",1,"hari gini masih minta jajan sama ortu, gak deh...",hari gini masih minta jajan sama ortu gak dehh...,hari gini masih minta jajan sama ortu gak dehh...
2,Instal snack Video diPlayStore atau dengan Ket...,1,instal snack video diplaystore atau dengan ket...,instal snack video diplaystore atau dengan ket...,instal snack video diplaystore atau dengan ket...
3,"Buka aplikasi SnackVideo, lalu log in dengan F...",1,"buka aplikasi snackvideo, lalu log in dengan f...",buka aplikasi snackvideo lalu log in dengan fb...,buka aplikasi snackvideo lalu log in dengan fb...
4,Untuk Tips and Trik Join Grupnya sebelum posti...,1,untuk tips and trik join grupnya sebelum posti...,untuk tips and trik join grupnya sebelum posti...,untuk tips and trik join grupnya sebelum posti...
...,...,...,...,...,...
995,Selamat siang&#10;Izin gabung dan izin share&#...,1,selamat siang&#10;izin gabung dan izin share&#...,selamat siang10izin gabung dan izin share10101...,selamat siangizin gabung dan izin sharedijual ...
996,Dijual Tanah Sawah Pinggir Jalan Raya&#10;Bisa...,1,dijual tanah sawah pinggir jalan raya&#10;bisa...,dijual tanah sawah pinggir jalan raya10bisa un...,dijual tanah sawah pinggir jalan rayabisa untu...
997,Rumah dijual Bogor kota. Spesifikasi pada gamb...,1,rumah dijual bogor kota. spesifikasi pada gamb...,rumah dijual bogor kota spesifikasi pada gamba...,rumah dijual bogor kota spesifikasi pada gamba...
998,jual tanah luas 25 hektar&#10;surat girik&#10;...,1,jual tanah luas 25 hektar&#10;surat girik&#10;...,jual tanah luas 25 hektar10surat girik10jual h...,jual tanah luas hektarsurat girikjual harga d...
999,Assalamu'alaikum Warahmatullahi Wabarakatuh &#...,1,assalamu'alaikum warahmatullahi wabarakatuh &#...,assalamualaikum warahmatullahi wabarakatuh 101...,assalamualaikum warahmatullahi wabarakatuh dij...

In [24]:
df.isna().sum()

pesan            1
label            0
text_lower       1
punc             0
remove_number    0
dtype: int64